# Syntax-1: [expression/value for variable in iterable] 
# For loop each time read value generated by iterable and evaluate 
# expression and store/append result into list. 


# Create list with sqrs al the numbers from 1 to 10 
# Without comprehension

A=[]
for num in range(1,11):
    A.append(num**2)
print(A)

# With comprehension
A=[num**2 for num in range(1,11)]
print(A)